cluster.name: "elasticsearch-cluster"
node.roles: [ master, data ]
discovery.type: multi-node

# cluster.initial_master_nodes:
#   - srv-co83i8i0si5c73b6ijag-0.elasticsearch-cluster:9300
#   - srv-co83i8i0si5c73b6ijag-1.elasticsearch-cluster:9300

discovery.seed_hosts:
  - srv-co83i8i0si5c73b6ijag-0.elasticsearch-cluster:9300
  - srv-co83i8i0si5c73b6ijag-1.elasticsearch-cluster:9300

# bind to all network interfaces
network.host: 0.0.0.0

xpack.security.enabled: false
